### ISSUE TITLE
transport: received unexpected content-type "application/json"

### ISSUE THREAD

**Issue by steled** [zitadel/terraform-provider-zitadel#242]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Version

2.1.0

### ZITADEL Version

3.0.4

### Describe the problem caused by this bug

After initially setting up my Zitadel instance (self-hosted docker compose solution) I get the following error when running terraform:

```shell
│ Error: failed to create project: rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "application/json"
│
│   with zitadel_project.test,
│   on project.tf line 1, in resource "zitadel_project" "test":
│    1: resource "zitadel_project" "test" {
```

See below my configuration:

### To reproduce

1. Use self-hosted solution using docker compose
2. Use terraform configuration
3. run terraform apply

### Screenshots

![Image](https://github.com/user-attachments/assets/f9338d2a-f6ee-43a5-abb6-3c63c2e42352)
![Image](https://github.com/user-attachments/assets/dec6f023-dfa8-495a-8ba5-c8fbc24dd5c3)

### Expected behavior

I expect that resources will be created without an error.

## docker

docker-compose.yaml
```yaml
services:
  zitadel:
    user: "${UID:-1000}"
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:v3.0.4'
    command: 'start-from-init --config /zitadel-config.yaml --config /zitadel-secrets.yaml  --masterkeyFile /zitadel-masterkey --tlsMode external'
    depends_on:
      db:
        condition: 'service_healthy'
    volumes:
      - './zitadel-config.yaml:/zitadel-config.yaml:ro'
      - './zitadel-secrets.yaml:/zitadel-secrets.yaml:ro'
      - './zitadel-init.yaml:/zitadel-init.yaml:ro'
      - './zitadel-masterkey:/zitadel-masterkey:ro'
      - './machinekey:/machinekey'
    ports:
      - '8080:8080'

  db:
    image: postgres:17-alpine3.21
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    networks:
      - 'zitadel'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s 
    volumes:
      - 'data:/var/lib/postgresql/data:rw'
      - 'backup:/backup'

networks:
  zitadel:

volumes:
  data: # files are available at /var/lib/docker/volumes/zitadel_data
  backup: # files are available at /var/lib/docker/volumes/zitadel_backup/_data
```

zitadel-config.yaml
```yaml
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
Log:
  Level: 'info'

# Make ZITADEL accessible over HTTPs, not HTTP
ExternalSecure: true # false
ExternalDomain: iam.k8s.test.de
ExternalPort: 443 # 8080

# If not using the docker compose example, adjust these values for connecting ZITADEL to your PostgreSQL
Database:
  postgres:
    Host: 'db'
    Port: 5432
    Database: zitadel
    User:
      SSL:
        Mode: 'disable'
    Admin:
      SSL:
        Mode: 'disable'

LogStore:
  Access:
    Stdout:
      Enabled: true
```

zitadel-secrets.yaml
```yaml
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml

# If not using the docker compose example, adjust these values for connecting ZITADEL to your PostgreSQL
Database:
  postgres:
    User:
      # If the user doesn't exist already, it is created
      Username: 'zitadel_user'
      Password: 'zitadel'
    Admin:
      Username: 'root'
      Password: 'postgres'
```

## terraform

main.tf
```tf
terraform {
  required_version = "~> 1.10.5"

  required_providers {
    zitadel = {
      source  = "zitadel/zitadel"
      version = "2.1.0"
    }
  }
}

provider "zitadel" {
  domain           = "iam.k8s.test.de"
  insecure         = "false"
  jwt_profile_file = "319991870480449539.json"
  port             = "443"
}
```

project.tf
```tf
resource "zitadel_project" "test" {
  name                     = "test"
  org_id                   = var.org_id
  project_role_assertion   = true
  project_role_check       = true
  has_project_check        = true
  private_labeling_setting = "PRIVATE_LABELING_SETTING_ENFORCE_PROJECT_RESOURCE_OWNER_POLICY"
}
```

variables.tf
```tf
variable "org_id" {
  default     = "319991761998970883"
  description = "Organization ID"
  type        = string
}
```
